name: Release Beta Workflow

on:
  issue_comment:
    types: [created]

jobs:
  generate_beta:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'trigger-beta' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      issues: read

    steps:
      - name: Check user permissions
        id: check_permissions
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const username = context.payload.comment.user.login;

            try {
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner,
                repo,
                username,
              });
              
              if (!['admin', 'write'].includes(permission.permission)) {
                core.setFailed('User does not have write access to the repository');
                return false;
              }
              return true;
            } catch (error) {
              core.setFailed('Failed to check user permissions');
              return false;
            }

      - name: Get PR Details
        if: steps.check_permissions.outputs.result == 'true'
        id: pr_details
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const prResponse = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.issue.number
            });
            const prTitle = prResponse.data.title;
            if (!prTitle.startsWith('chore: sync branches')) {
              core.setFailed('PR title does not start with "chore: sync branches"');
              return;
            }
            return { prTitle };

      - name: Checkout PR Code
        if: steps.check_permissions.outputs.result == 'true'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          ref: ${{ steps.pr_details.outputs.ref }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get version from pubspec (PR branch)
        if: steps.check_permissions.outputs.result == 'true'
        id: get_version
        run: |
          if [ ! -f pubspec.yaml ]; then
            echo "pubspec.yaml not found"
            exit 1
          fi
          VERSION=$(grep '^version:' pubspec.yaml | cut -d' ' -f2 | tr -d '\r')
          if [ -z "$VERSION" ]; then
            echo "Version not found in pubspec.yaml"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate unique tag name
        if: steps.check_permissions.outputs.result == 'true'
        id: generate_tag
        run: |
          BASE_TAG="internal-v${{ steps.get_version.outputs.version }}"
          if ! git rev-parse "$BASE_TAG" >/dev/null 2>&1; then
            echo "tag_name=$BASE_TAG" >> $GITHUB_OUTPUT
          else
            counter=1
            while git rev-parse "$BASE_TAG+$counter" >/dev/null 2>&1; do
              counter=$((counter + 1))
            done
            echo "tag_name=$BASE_TAG+$counter" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_permissions.outputs.result == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.generate_tag.outputs.tag_name }} -m "Beta release ${{ steps.generate_tag.outputs.tag_name }}"
          git push origin ${{ steps.generate_tag.outputs.tag_name }}

      - name: Create Release
        if: steps.check_permissions.outputs.result == 'true'
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag_name }}
          name: Beta Release ${{ steps.generate_tag.outputs.tag_name }}
          generate_release_notes: true
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.MOBILE_APPS_PAT }}

      - name: Wait for Bitrise Build
        if: steps.check_permissions.outputs.result == 'true'
        id: wait_build
        env:
          BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
          BITRISE_PAT: ${{ secrets.BITRISE_PAT }}
        run: |
          # Wait for build to appear (it might take a few seconds after tag creation)
          sleep 30

          # Initialize build_slug as empty
          BUILD_SLUG=""

          # First, find the build with matching tag
          while [ -z "$BUILD_SLUG" ]; do
            echo "Searching for build with tag: ${{ steps.tag_info.outputs.tag_name }}"
            
            # Get recent builds
            BUILDS=$(curl -s https://api.bitrise.io/v0.1/apps/$BITRISE_APP_ID/builds?limit=10 \
              --header "Authorization: $BITRISE_PAT")
            
            # Check if response contains data array
            if ! echo "$BUILDS" | jq -e '.data' > /dev/null; then
              echo "Error: API response does not contain 'data' array"
              echo "Full API Response:"
              echo "$BUILDS"
              echo "Waiting 30 seconds before retry..."
              sleep 30
              continue
            fi
            
            # Extract build slug and number for the matching tag
            BUILD_INFO=$(echo "$BUILDS" | jq -r --arg TAG "${{ steps.tag_info.outputs.tag_name }}" \
              '.data[] | select(.tag == $TAG) | {slug: .slug, build_number: .build_number}' | jq -s '.[0]')
            
            if [ -n "$BUILD_INFO" ] && [ "$BUILD_INFO" != "null" ]; then
              BUILD_SLUG=$(echo "$BUILD_INFO" | jq -r '.slug')
              BUILD_NUMBER=$(echo "$BUILD_INFO" | jq -r '.build_number')
              echo "Found build! Slug: $BUILD_SLUG, Number: $BUILD_NUMBER"
              echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
            else
              echo "No build found yet. Waiting 30 seconds..."
              sleep 30
            fi
          done

          # Now that we have the build slug, only check this specific build's status
          while true; do
            echo "Checking status of build: $BUILD_NUMBER"
            
            # Get status of specific build
            BUILD_STATUS=$(curl -s "https://api.bitrise.io/v0.1/apps/$BITRISE_APP_ID/builds/$BUILD_SLUG" \
              --header "Authorization: $BITRISE_PAT" | jq -r '.data.status_text')
            
            echo "Current build status: $BUILD_STATUS"
            
            if [ "$BUILD_STATUS" = "success" ]; then
              echo "Build succeeded!"
              exit 0
            elif [ "$BUILD_STATUS" = "failed" ] || [ "$BUILD_STATUS" = "aborted" ]; then
              echo "Build failed with status: $BUILD_STATUS"
              exit 1
            fi
            
            echo "Build still in progress. Waiting 30 seconds..."
            sleep 30
          done

      - name: Send Success Slack Notification
        if: steps.check_permissions.outputs.result == 'true' && steps.wait_build.outcome == 'success'
        uses: ./.github/actions/beta_notif
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_SLACK_WEBHOOK_URL }}
          BETA_VERSION: ${{ steps.generate_tag.outputs.tag_name }}

      - name: Comment on PR if user lacks permission
        if: steps.check_permissions.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.issue.number,
              body: '❌ Unable to trigger beta release: You do not have write access to this repository.'
            });
